[package]
name = "copper"
version = "0.1.0"
authors = ["mp768 <60555816+mp768@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]